logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  file:
    max-size: 20M

spring:
  datasource:
    url: jdbc:mysql://47.106.210.62/operation
    username: root
    password: ENC(fzdFFXTdehoQKA19orCJeySVBL5TpHNb)
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
    hikari:
